<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Data extends Model
{
    use HasFactory;

    // Tentukan kolom yang bisa diisi secara massal (mass assignment)
    protected $fillable = [
        'user_id', 

    //Untuk jenis orbit
        'jenis_orbit',
        'inklinasi',
        'userlat_up',
        'userlong_up',
        'spaceslot_up',
        'slantrangetouser_up_input',
        'userelevationangel_up_input',
        'userazimuthangle_up_input',
        'earthcentralangle_up_input',


        'userlat_down',
        'userlong_down',
        'spaceslot_down',
        'slantrangetouser_down_input',
        'userelevationangel_down_input',
        'userazimuthangle_down_input',
        'earthcentralangle_down_input',

        'ketinggian',
        'apogee',
        'perigee',
        'eccentricity',
        'argumenop',
        'raan',
        'elevasi',
        'altitude',
        'radius',
        'slant_range',
        
    //Untuk Frek
        'frekuensi_satuan',
        'frekuensi',
        'panjang_gelombang',
        'path_loss',
        'frekuensi_downlink',
        'panjang_gelombang_downlink',
        'path_loss_downlink',
        
    //Untuk Transmitter
        'watt_up',
        'dbw_up', 
        'dbm_up',
        'alength_up',
        'blength_up',
        'clength_up',
        'totlength_up',
        'cabletype_up',
        'guideloss_up',
        'totalloss_up',
        'connect_up',
        'totconnect_up',
        'filter_up',
        'device_up',
        'devicee_up',
        'atn_up' ,
        'totlinelosses_up',
        'totpowerdeliv_up',

        'watt_down',
        'dbw_down' ,
        'dbm_down' ,
        'alength_down' ,
        'blength_down' ,
        'clength_down' ,
        'totlength_down' ,
        'cabletype_down' ,
        'guideloss_down' ,
        'totalloss_down' ,
        'connect_down' ,
        'totconnect_down',
        'filter_down' ,
        'device_down' ,
        'devicee_down',
        'atn_down',
        'totlinelosses_down' ,
        'totrfpowerdeliv_down',

    //Untuk Receiver
        'cabletype_uprec',
        'typecable',
        'alength_uprec',
        'blength_uprec',
        'clength_uprec',
        'la_uprec',
        'lb_uprec',
        'lc_uprec',
        'lbpf_uprec',
        'lother_uprec',
        'connect_uprec',
        'totconnect_uprec',
        'antenna to lna_uprec',
        'tranlincoe_uprec',
        'antemper_uprec',
        'spactemp_uprec',
        'tlna_uprec',
        'lnagain_uprec',
        'glna_uprec',
        '2ndstagetemp_uprec',
        'ts_uprec',

        'cabletype_downrec',
        'typecable_downrec',
        'alength_downrec',
        'blength_downrec',
        'clength_downrec',
        'la_downrec',
        'lb_downrec',
        'lc_downrec',
        'lbpf_downrec',
        'lother_downrec',
        'connect_downrec',
        'totconnect_downrec',
        'antenna_to_lna_downrec',
        'tranlincoe_downrec',
        'antemper_downrec',
        'spactemp_downrec',
        'tlna_downrec',
        'lnagain_downrec',
        'glna_downrec',
        'dtype_downrec',
        'dloss_length_downrec',
        'dloss_per_meter_downrec',
        'dloss_result_downrec',
        'tcomrcvr_downrec',
        'ts_downrec',

    //Untuk calcazimuth,
        'latitude_up',  
        'innhem_up',
        'innhem2_up',
        'longitude_up',
        'eastofsat_up' ,
        'eastofsat2_up',
        'sat_in_quad_up',
        'quad_result_up',
        'quad_angle_range_up',
        'sat_in_quad_value_up',
        'quad_result_value_up',
        'quad_angle_range_value_up',
        'sat_in_quad_value2_up',
        'quad_result_value2_up',
        'quad_angle_range_value2_up',
        'sat_in_quad_value3_up',
        'quad_result_value3_up',
        'quad_angle_range_value3_up',
        'azimuthcalc_up',
        'azimuthresult_up',

        'latitude_down',
        'innhem_down',
        'innhem2_down',
        'longitude_down',
        'eastofsat_down' ,
        'eastofsat2_down',
        'sat_in_quad_down',
        'quad_result_down',
        'quad_angle_range_down',
        'sat_in_quad_value_down',
        'quad_result_value_down',
        'quad_angle_range_value_down',
        'sat_in_quad_value2_down',
        'quad_result_value2_down',
        'quad_angle_range_value2_down',
        'sat_in_quad_value3_down',
        'quad_result_value3_down',
        'quad_angle_range_value3_down',
        'azimuthcalc_down',
        'azimuthresult_down',

    //Untuk Antenna Gain
        'jenis_polarizationgrounds_up',
        'jenis_antenagrounds_up',
        'frequency_upgrounds',
        'wavelength_upgrounds' ,
        'gain_manual_upgrounds' ,
        'beamwidth_manual_upgrounds' ,

        'jenis_polarizationspacecraft_up' ,
        'jenis_antenaspacecraft_up' ,
        'gain_manual_upspacecraft' ,
        'beamwidth_manual_upspacecraft' ,

        'jenis_polarizationgrounds_down',
        'jenis_antenagrounds_down' ,
        'frequency_downgrounds' ,
        'wavelength_downgrounds' ,
        'gain_manual_downgrounds' ,
        'beamwidth_manual_downgrounds' ,
        
        'jenis_polarizationspacecraft_down' ,
        'jenis_antenaspacecraft_down' ,
        'gain_manual_downspacecraft' ,
        'beamwidth_manual_downspacecraft',

    //Untuk Antenna Pointing Loss
        'jenis_polarizationgrounds_up_poin',
        'frequency_upgrounds_poin',
        'wavelength_upgrounds_poin',
        'gain_upgrounds_poin',
        'beamwidth_upgrounds_poin',
        'estimedpointingerror_upgrounds_θ1_poin',
        'annrolloff_upgrounds_poin',
        'approxannpoinloss_upgrounds_poin',
        'jenis_polarizationspacecraft_up_poin',
        'gain_upspacecraft_poin',
        'beamwidth_upspacecraft_poin',
        'upspacecraft_θ2_poin',
        'calculation_formulas_upspacecraft_poin',
        'approxannpoinloss_upspacecraft_poin',
        'jenis_polarizationspacecraft_down_poin',
        'gain_downspacecraft_poin',
        'beamwidth_downspacecraft_poin',
        'downspacecraft_θ3_poin',
        'calculation_formulas_downspacecraft_poin',
        'approxannpoinloss_downspacecraft_poin',
        'jenis_polarizationgrounds_down_poin',
        'frequency_downgrounds_poin',
        'wavelength_downgrounds_poin',
        'gain_downgrounds_poin',
        'beamwidth_downgrounds_poin',
        'upgrounds_θ4_poin',
        'annrolloff_downgrounds_poin',
        'approxannpoinloss_downgrounds_poin',
        
        
    //Untuk Antenna Polarization Loss
        'axtxantenna_up',
        'axialratio1_up',
        'axrxantenna_up',
        'axialratio2_up',
        'degrees_up',
        'radians_up',
        'polarizationloss_up',
        'hasilpolarizationloss_up',
        'crosspolpowerfraction_up',
        'dbcrosspolpowerfraction_up',
        'crosspolarizationisolation_up',

        'axtxantenna_down',
        'axialratio1_down',
        'axrxantenna_down',
        'axialratio2_down',
        'degrees_down',
        'radians_down',
        'polarizationloss_down',
        'hasilpolarizationloss_down',
        'crosspolpowerfraction_down',
        'dbcrosspolpowerfraction_down',
        'crosspolarizationisolation_down',


    //Untuk AttmosIonos
        'min_elevation_angle',
        'loss_determined_atmospheric',
        'uplink_loss_determined_display',
        'uplink_frequency',
        'uplink_loss_ionosphere',
        'downlink_loss_determined_display',
        'downlink_frequency',
        'downlink_loss_ionosphere',

    //Untuk Uplink & Downlink Budget
        'tx_powerwatts_up',
        'tx_powerdbw_up' ,
        'tx_powerdbm_up' ,
        'trlinelosses_up' ,
        'antennaagain_up' ,
        'eirp_up' ,
        'pointinglosses_up' ,
        'polarizationlosses_up' ,
        'pathlosss_up' ,
        'atmosphericlosses_up' ,
        'ionosphericlosses_up' ,
        'rainlosses_up' ,
        'signallevel_up' ,
        'scpointingloss_up' ,
        'scantennagain_up' ,
        'sclinelosses_up' ,
        'scnoisetemp_up' ,
        'scgtratio_up' ,
        'scsignalpower_up' ,
        'scbandwidth_up' ,
        'scnoisepower_up' ,
        'snrratio_up' ,
        'requiredsnr_up' ,
        'linkmargin_up' ,
        'sc_powerwatts_down' ,
        'sc_powerdbw_down' ,
        'sc_powerdbm_down' ,
        'sclinelosses_down' ,
        'scantennaagain_down' ,
        'sceirp_down' ,
        'scpointinglosses_down' ,
        'polarizationlosses_down' ,
        'pathlosss_down' ,
        'atmosphericlosses_down' ,
        'ionosphericlosses_down' ,
        'rainlosses_down' ,
        'signallevel_down' ,
        'gspointingloss_down' ,
        'gsantennagain_down' ,
        'gslinelosses_down' ,
        'gsnoisetemp_down' ,
        'gsgtratio_down' ,
        'gssignalpower_down' ,
        'gsbandwidth_down' ,
        'gsnoisepower_down' ,
        'snrratio_down' ,
        'requiredsnr_down' ,
        'linkmargin_down' ,

    ];

    // Relasi ke tabel User
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
